<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mod2MultplLM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Mod2MultplLM_files/libs/clipboard/clipboard.min.js"></script>
<script src="Mod2MultplLM_files/libs/quarto-html/quarto.js"></script>
<script src="Mod2MultplLM_files/libs/quarto-html/popper.min.js"></script>
<script src="Mod2MultplLM_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Mod2MultplLM_files/libs/quarto-html/anchor.min.js"></script>
<link href="Mod2MultplLM_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Mod2MultplLM_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Mod2MultplLM_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Mod2MultplLM_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Mod2MultplLM_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mod2MultplLM</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="quarto" class="level2">
<h2 class="anchored" data-anchor-id="quarto">Quarto</h2>
<p>Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <a href="https://quarto.org" class="uri">https://quarto.org</a>.</p>
</section>
<section id="running-code" class="level2">
<h2 class="anchored" data-anchor-id="running-code">Running Code</h2>
<p>When you click the <strong>Render</strong> button a document will be generated that includes both content and the output of embedded code. You can embed code like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.1.0 ──
✔ broom        1.0.4     ✔ rsample      1.1.1
✔ dials        1.2.0     ✔ tune         1.1.1
✔ infer        1.0.4     ✔ workflows    1.1.3
✔ modeldata    1.1.0     ✔ workflowsets 1.0.1
✔ parsnip      1.1.0     ✔ yardstick    1.2.0
✔ recipes      1.0.6     
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Use suppressPackageStartupMessages() to eliminate package startup messages</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loaded glmnet 4.1-7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo

Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can add options to executable code like this</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>bike <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"bike_cleaned-3.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 17379 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): dteday, season, mnth, holiday, weekday, workingday, weathersit
dbl (9): instant, hr, temp, atemp, hum, windspeed, casual, registered, count

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bike)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 17,379
Columns: 16
$ instant    &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …
$ dteday     &lt;chr&gt; "1/1/2011", "1/1/2011", "1/1/2011", "1/1/2011", "1/1/2011",…
$ season     &lt;chr&gt; "Winter", "Winter", "Winter", "Winter", "Winter", "Winter",…
$ mnth       &lt;chr&gt; "Jan", "Jan", "Jan", "Jan", "Jan", "Jan", "Jan", "Jan", "Ja…
$ hr         &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
$ holiday    &lt;chr&gt; "NotHoliday", "NotHoliday", "NotHoliday", "NotHoliday", "No…
$ weekday    &lt;chr&gt; "Saturday", "Saturday", "Saturday", "Saturday", "Saturday",…
$ workingday &lt;chr&gt; "NotWorkingDay", "NotWorkingDay", "NotWorkingDay", "NotWork…
$ weathersit &lt;chr&gt; "NoPrecip", "NoPrecip", "NoPrecip", "NoPrecip", "NoPrecip",…
$ temp       &lt;dbl&gt; 0.24, 0.22, 0.22, 0.24, 0.24, 0.24, 0.22, 0.20, 0.24, 0.32,…
$ atemp      &lt;dbl&gt; 0.2879, 0.2727, 0.2727, 0.2879, 0.2879, 0.2576, 0.2727, 0.2…
$ hum        &lt;dbl&gt; 0.81, 0.80, 0.80, 0.75, 0.75, 0.75, 0.80, 0.86, 0.75, 0.76,…
$ windspeed  &lt;dbl&gt; 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0896, 0.0000, 0.0…
$ casual     &lt;dbl&gt; 3, 8, 5, 3, 0, 0, 2, 1, 1, 8, 12, 26, 29, 47, 35, 40, 41, 1…
$ registered &lt;dbl&gt; 13, 32, 27, 10, 1, 1, 0, 2, 7, 6, 24, 30, 55, 47, 71, 70, 5…
$ count      &lt;dbl&gt; 16, 40, 32, 13, 1, 1, 2, 3, 8, 14, 36, 56, 84, 94, 106, 110…</code></pre>
</div>
</div>
<p>The <code>echo: false</code> option disables the printing of code (only output is displayed).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>bike <span class="ot">=</span> bike <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">dteday =</span> <span class="fu">mdy</span>(dteday))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>bike <span class="ot">=</span> bike <span class="sc">%&gt;%</span> <span class="fu">mutate_if</span>(is.character, as_factor)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>bike <span class="ot">=</span> bike <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">hr =</span> <span class="fu">as_factor</span>(hr))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>bike</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17,379 × 16
   instant dteday     season mnth  hr    holiday   weekday workingday weathersit
     &lt;dbl&gt; &lt;date&gt;     &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;     &lt;fct&gt;   &lt;fct&gt;      &lt;fct&gt;     
 1       1 2011-01-01 Winter Jan   0     NotHolid… Saturd… NotWorkin… NoPrecip  
 2       2 2011-01-01 Winter Jan   1     NotHolid… Saturd… NotWorkin… NoPrecip  
 3       3 2011-01-01 Winter Jan   2     NotHolid… Saturd… NotWorkin… NoPrecip  
 4       4 2011-01-01 Winter Jan   3     NotHolid… Saturd… NotWorkin… NoPrecip  
 5       5 2011-01-01 Winter Jan   4     NotHolid… Saturd… NotWorkin… NoPrecip  
 6       6 2011-01-01 Winter Jan   5     NotHolid… Saturd… NotWorkin… Misty     
 7       7 2011-01-01 Winter Jan   6     NotHolid… Saturd… NotWorkin… NoPrecip  
 8       8 2011-01-01 Winter Jan   7     NotHolid… Saturd… NotWorkin… NoPrecip  
 9       9 2011-01-01 Winter Jan   8     NotHolid… Saturd… NotWorkin… NoPrecip  
10      10 2011-01-01 Winter Jan   9     NotHolid… Saturd… NotWorkin… NoPrecip  
# ℹ 17,369 more rows
# ℹ 7 more variables: temp &lt;dbl&gt;, atemp &lt;dbl&gt;, hum &lt;dbl&gt;, windspeed &lt;dbl&gt;,
#   casual &lt;dbl&gt;, registered &lt;dbl&gt;, count &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Question 1 Which of the quantitative variables appears to be best correlated with “count”? temp</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike, <span class="fu">aes</span>(<span class="at">x=</span>season,<span class="at">y=</span>count)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Mod2MultplLM_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike, <span class="fu">aes</span>(<span class="at">x=</span>season,<span class="at">y=</span>count)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Mod2MultplLM_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Question 2 Which “season” appears to have the highest count of rides? Summer</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>bike_recipe <span class="ot">=</span> <span class="fu">recipe</span>(count <span class="sc">~</span> hr, bike) <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(hr)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">=</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>lm_wflow <span class="ot">=</span> </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lm_model) <span class="sc">%&gt;%</span> </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(bike_recipe)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">=</span> <span class="fu">fit</span>(lm_wflow, bike)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fit<span class="sc">$</span>fit<span class="sc">$</span>fit<span class="sc">$</span>fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = ..y ~ ., data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-446.45  -60.99   -6.01   50.10  551.49 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   53.898      4.756  11.332  &lt; 2e-16 ***
hr_X1        -20.522      6.731  -3.049 0.002300 ** 
hr_X2        -31.028      6.752  -4.595 4.35e-06 ***
hr_X3        -42.171      6.796  -6.205 5.58e-10 ***
hr_X4        -47.545      6.796  -6.996 2.73e-12 ***
hr_X5        -34.008      6.747  -5.040 4.70e-07 ***
hr_X6         22.146      6.729   3.291 0.000999 ***
hr_X7        158.167      6.724  23.523  &lt; 2e-16 ***
hr_X8        305.113      6.724  45.377  &lt; 2e-16 ***
hr_X9        165.411      6.724  24.600  &lt; 2e-16 ***
hr_X10       119.770      6.724  17.812  &lt; 2e-16 ***
hr_X11       154.245      6.724  22.939  &lt; 2e-16 ***
hr_X12       199.418      6.722  29.668  &lt; 2e-16 ***
hr_X13       199.763      6.719  29.729  &lt; 2e-16 ***
hr_X14       187.051      6.719  27.838  &lt; 2e-16 ***
hr_X15       197.335      6.719  29.368  &lt; 2e-16 ***
hr_X16       258.085      6.717  38.422  &lt; 2e-16 ***
hr_X17       407.554      6.717  60.674  &lt; 2e-16 ***
hr_X18       371.613      6.722  55.286  &lt; 2e-16 ***
hr_X19       257.625      6.722  38.327  &lt; 2e-16 ***
hr_X20       172.132      6.722  25.608  &lt; 2e-16 ***
hr_X21       118.416      6.722  17.617  &lt; 2e-16 ***
hr_X22        77.437      6.722  11.520  &lt; 2e-16 ***
hr_X23        33.933      6.722   5.048 4.50e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 128.2 on 17355 degrees of freedom
Multiple R-squared:  0.5015,    Adjusted R-squared:  0.5008 
F-statistic: 759.1 on 23 and 17355 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Question 3: How many Dummy(indicator) variables are therein hr? 23</p>
<p>Question 4: Which hour is selected as the base level of the category? 6</p>
<p>Question 5: During which hour of the day does the model predict the highest number of rides? 17</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>bike_recipe <span class="ot">=</span> <span class="fu">recipe</span>(count <span class="sc">~</span> hr, bike) <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(hr)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">=</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>lm_wflow <span class="ot">=</span> </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lm_model) <span class="sc">%&gt;%</span> </span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(bike_recipe)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">=</span> <span class="fu">fit</span>(lm_wflow, bike)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fit<span class="sc">$</span>fit<span class="sc">$</span>fit<span class="sc">$</span>fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = ..y ~ ., data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-446.45  -60.99   -6.01   50.10  551.49 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   53.898      4.756  11.332  &lt; 2e-16 ***
hr_X1        -20.522      6.731  -3.049 0.002300 ** 
hr_X2        -31.028      6.752  -4.595 4.35e-06 ***
hr_X3        -42.171      6.796  -6.205 5.58e-10 ***
hr_X4        -47.545      6.796  -6.996 2.73e-12 ***
hr_X5        -34.008      6.747  -5.040 4.70e-07 ***
hr_X6         22.146      6.729   3.291 0.000999 ***
hr_X7        158.167      6.724  23.523  &lt; 2e-16 ***
hr_X8        305.113      6.724  45.377  &lt; 2e-16 ***
hr_X9        165.411      6.724  24.600  &lt; 2e-16 ***
hr_X10       119.770      6.724  17.812  &lt; 2e-16 ***
hr_X11       154.245      6.724  22.939  &lt; 2e-16 ***
hr_X12       199.418      6.722  29.668  &lt; 2e-16 ***
hr_X13       199.763      6.719  29.729  &lt; 2e-16 ***
hr_X14       187.051      6.719  27.838  &lt; 2e-16 ***
hr_X15       197.335      6.719  29.368  &lt; 2e-16 ***
hr_X16       258.085      6.717  38.422  &lt; 2e-16 ***
hr_X17       407.554      6.717  60.674  &lt; 2e-16 ***
hr_X18       371.613      6.722  55.286  &lt; 2e-16 ***
hr_X19       257.625      6.722  38.327  &lt; 2e-16 ***
hr_X20       172.132      6.722  25.608  &lt; 2e-16 ***
hr_X21       118.416      6.722  17.617  &lt; 2e-16 ***
hr_X22        77.437      6.722  11.520  &lt; 2e-16 ***
hr_X23        33.933      6.722   5.048 4.50e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 128.2 on 17355 degrees of freedom
Multiple R-squared:  0.5015,    Adjusted R-squared:  0.5008 
F-statistic: 759.1 on 23 and 17355 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lm_fit, <span class="at">new_data =</span> <span class="fu">data.frame</span>(<span class="at">hr =</span> <span class="fu">c</span>(<span class="st">"0"</span>,<span class="st">"1"</span>,<span class="st">"2"</span>,<span class="st">"3"</span>,<span class="st">"4"</span>,<span class="st">"5"</span>,<span class="st">"6"</span>,<span class="st">"7"</span>,<span class="st">"8"</span>,<span class="st">"9"</span>,<span class="st">"10"</span>,<span class="st">"11"</span>,<span class="st">"12"</span>,<span class="st">"13"</span>,<span class="st">"14"</span>,<span class="st">"15"</span>,<span class="st">"16"</span>,<span class="st">"17"</span>,<span class="st">"18"</span>,<span class="st">"19"</span>,<span class="st">"20"</span>,<span class="st">"21"</span>,<span class="st">"22"</span>,<span class="st">"23"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 1
    .pred
    &lt;dbl&gt;
 1  53.9 
 2  33.4 
 3  22.9 
 4  11.7 
 5   6.35
 6  19.9 
 7  76.0 
 8 212.  
 9 359.  
10 219.  
# ℹ 14 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike, <span class="fu">aes</span>(<span class="at">x=</span>temp,<span class="at">y=</span>count)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Continuous x aesthetic
ℹ did you forget `aes(group = ...)`?</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Mod2MultplLM_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bike, <span class="fu">aes</span>(<span class="at">x=</span>temp,<span class="at">y=</span>count)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Continuous x aesthetic
ℹ did you forget `aes(group = ...)`?</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Mod2MultplLM_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Question 6: Which statement bets describes the general relationship between “temp” and “count”? A. As “temp” increases, “count” appears to generally increase.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>bike2 <span class="ot">=</span> bike <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">"count"</span>, <span class="st">"hr"</span>, <span class="st">"temp"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>bike3 <span class="ot">=</span> <span class="fu">lm</span>(count <span class="sc">~</span>., bike2) <span class="co">#use the ~. to include all predictors rather than typing them all in</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bike3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count ~ ., data = bike2)

Residuals:
    Min      1Q  Median      3Q     Max 
-469.96  -63.29   -6.93   52.41  519.88 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -80.181      4.848 -16.539  &lt; 2e-16 ***
hr1          -18.214      6.111  -2.981  0.00288 ** 
hr2          -27.346      6.131  -4.461 8.22e-06 ***
hr3          -38.069      6.170  -6.170 6.99e-10 ***
hr4          -41.584      6.171  -6.739 1.65e-11 ***
hr5          -25.033      6.128  -4.085 4.42e-05 ***
hr6           32.169      6.111   5.264 1.43e-07 ***
hr7          166.290      6.106  27.233  &lt; 2e-16 ***
hr8          308.675      6.105  50.561  &lt; 2e-16 ***
hr9          162.739      6.105  26.657  &lt; 2e-16 ***
hr10         110.256      6.107  18.055  &lt; 2e-16 ***
hr11         138.410      6.110  22.652  &lt; 2e-16 ***
hr12         178.516      6.112  29.206  &lt; 2e-16 ***
hr13         174.714      6.114  28.574  &lt; 2e-16 ***
hr14         159.035      6.118  25.995  &lt; 2e-16 ***
hr15         168.304      6.119  27.505  &lt; 2e-16 ***
hr16         230.103      6.116  37.625  &lt; 2e-16 ***
hr17         382.550      6.112  62.588  &lt; 2e-16 ***
hr18         350.451      6.112  57.334  &lt; 2e-16 ***
hr19         241.342      6.108  39.510  &lt; 2e-16 ***
hr20         160.317      6.106  26.257  &lt; 2e-16 ***
hr21         110.416      6.104  18.089  &lt; 2e-16 ***
hr22          72.533      6.103  11.885  &lt; 2e-16 ***
hr23          31.748      6.103   5.202 1.99e-07 ***
temp         286.855      4.715  60.836  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 116.3 on 17354 degrees of freedom
Multiple R-squared:  0.5891,    Adjusted R-squared:  0.5886 
F-statistic:  1037 on 24 and 17354 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>emptybike <span class="ot">=</span> <span class="fu">lm</span>(count <span class="sc">~</span><span class="dv">1</span>, bike2) <span class="co">#use ~1 to build an empty model </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(emptybike)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count ~ 1, data = bike2)

Residuals:
    Min      1Q  Median      3Q     Max 
-188.46 -149.46  -47.46   91.54  787.54 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  189.463      1.376   137.7   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 181.4 on 17378 degrees of freedom</code></pre>
</div>
</div>
<p>Question 7: What is the value of the slope coefficient for “hr23” in this model? 31.748</p>
<p>Question 8: What is the adjusted R squared value? 0.5886</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>bike4 <span class="ot">=</span> bike <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">"count"</span>, <span class="st">"atemp"</span>, <span class="st">"temp"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>bike5 <span class="ot">=</span> <span class="fu">lm</span>(count <span class="sc">~</span>., bike4) <span class="co">#use the ~. to include all predictors rather than typing them all in</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bike5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count ~ ., data = bike4)

Residuals:
    Min      1Q  Median      3Q     Max 
-293.47 -109.95  -32.87   76.57  744.57 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -1.898      3.904  -0.486    0.627    
atemp         49.407     46.773   1.056    0.291    
temp         337.744     41.744   8.091 6.31e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 165.9 on 17376 degrees of freedom
Multiple R-squared:  0.1639,    Adjusted R-squared:  0.1638 
F-statistic:  1703 on 2 and 17376 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>emptybike2 <span class="ot">=</span> <span class="fu">lm</span>(count <span class="sc">~</span><span class="dv">1</span>, bike4) <span class="co">#use ~1 to build an empty model </span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(emptybike)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count ~ 1, data = bike2)

Residuals:
    Min      1Q  Median      3Q     Max 
-188.46 -149.46  -47.46   91.54  787.54 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  189.463      1.376   137.7   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 181.4 on 17378 degrees of freedom</code></pre>
</div>
</div>
<p>Question 9: What is the adjusted R squared value? 0.1638</p>
<p>Question 10: Which of the two variables in the model are significant? temp only</p>
<p>Question 11: The model likely demonstrates which phenomenon? Multicollinearity</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>bike6 <span class="ot">=</span> bike <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">"count"</span>,<span class="st">"season"</span>, <span class="st">"mnth"</span>, <span class="st">"hr"</span>, <span class="st">"holiday"</span>, <span class="st">"weekday"</span>, <span class="st">"workingday"</span>, <span class="st">"weathersit"</span>, <span class="st">"temp"</span>, <span class="st">"atemp"</span>, <span class="st">"hum"</span>, <span class="st">"windspeed"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>bike6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17,379 × 12
   count season mnth  hr    holiday    weekday workingday weathersit  temp atemp
   &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;      &lt;fct&gt;   &lt;fct&gt;      &lt;fct&gt;      &lt;dbl&gt; &lt;dbl&gt;
 1    16 Winter Jan   0     NotHoliday Saturd… NotWorkin… NoPrecip    0.24 0.288
 2    40 Winter Jan   1     NotHoliday Saturd… NotWorkin… NoPrecip    0.22 0.273
 3    32 Winter Jan   2     NotHoliday Saturd… NotWorkin… NoPrecip    0.22 0.273
 4    13 Winter Jan   3     NotHoliday Saturd… NotWorkin… NoPrecip    0.24 0.288
 5     1 Winter Jan   4     NotHoliday Saturd… NotWorkin… NoPrecip    0.24 0.288
 6     1 Winter Jan   5     NotHoliday Saturd… NotWorkin… Misty       0.24 0.258
 7     2 Winter Jan   6     NotHoliday Saturd… NotWorkin… NoPrecip    0.22 0.273
 8     3 Winter Jan   7     NotHoliday Saturd… NotWorkin… NoPrecip    0.2  0.258
 9     8 Winter Jan   8     NotHoliday Saturd… NotWorkin… NoPrecip    0.24 0.288
10    14 Winter Jan   9     NotHoliday Saturd… NotWorkin… NoPrecip    0.32 0.348
# ℹ 17,369 more rows
# ℹ 2 more variables: hum &lt;dbl&gt;, windspeed &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>allmod <span class="ot">=</span> <span class="fu">lm</span>(count <span class="sc">~</span>., bike6) </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(allmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count ~ ., data = bike6)

Residuals:
    Min      1Q  Median      3Q     Max 
-401.19  -61.46   -9.25   51.13  478.91 

Coefficients: (1 not defined because of singularities)
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            -12.7473     7.0760  -1.801 0.071642 .  
seasonSpring            39.4906     5.2578   7.511 6.16e-14 ***
seasonSummer            28.8578     6.2248   4.636 3.58e-06 ***
seasonFall              66.0479     5.2858  12.495  &lt; 2e-16 ***
mnthFeb                 -0.4609     4.2442  -0.109 0.913527    
mnthMar                  4.4203     4.7679   0.927 0.353884    
mnthApr                 -9.1995     7.0836  -1.299 0.194061    
mnthMay                  0.5152     7.5761   0.068 0.945784    
mnthJun                -20.7340     7.7826  -2.664 0.007726 ** 
mnthJul                -40.7689     8.7337  -4.668 3.06e-06 ***
mnthAug                -15.6046     8.5184  -1.832 0.066988 .  
mnthSep                 15.5058     7.5733   2.047 0.040630 *  
mnthOct                  3.9416     7.0161   0.562 0.574259    
mnthNov                -15.5826     6.7536  -2.307 0.021049 *  
mnthDec                 -9.3163     5.3638  -1.737 0.082422 .  
hr1                    -16.4977     5.7874  -2.851 0.004369 ** 
hr2                    -24.4135     5.8076  -4.204 2.64e-05 ***
hr3                    -34.3153     5.8494  -5.866 4.53e-09 ***
hr4                    -36.0087     5.8549  -6.150 7.91e-10 ***
hr5                    -19.7552     5.8171  -3.396 0.000685 ***
hr6                     38.7841     5.8019   6.685 2.38e-11 ***
hr7                    172.8931     5.7906  29.857  &lt; 2e-16 ***
hr8                    311.6446     5.7839  53.882  &lt; 2e-16 ***
hr9                    161.5087     5.7898  27.895  &lt; 2e-16 ***
hr10                   104.2107     5.8133  17.926  &lt; 2e-16 ***
hr11                   127.0021     5.8555  21.689  &lt; 2e-16 ***
hr12                   164.1738     5.9046  27.804  &lt; 2e-16 ***
hr13                   157.7321     5.9447  26.533  &lt; 2e-16 ***
hr14                   141.0138     5.9777  23.590  &lt; 2e-16 ***
hr15                   150.1886     5.9891  25.077  &lt; 2e-16 ***
hr16                   212.6712     5.9768  35.583  &lt; 2e-16 ***
hr17                   367.4906     5.9425  61.841  &lt; 2e-16 ***
hr18                   337.0098     5.9042  57.080  &lt; 2e-16 ***
hr19                   230.4248     5.8499  39.390  &lt; 2e-16 ***
hr20                   152.5053     5.8186  26.210  &lt; 2e-16 ***
hr21                   104.5791     5.7953  18.045  &lt; 2e-16 ***
hr22                    68.8433     5.7847  11.901  &lt; 2e-16 ***
hr23                    30.9933     5.7800   5.362 8.33e-08 ***
holidayHoliday         -26.3866     5.2846  -4.993 6.00e-07 ***
weekdaySunday          -14.7269     3.1158  -4.727 2.30e-06 ***
weekdayMonday           -6.6593     3.2160  -2.071 0.038401 *  
weekdayTuesday          -5.4421     3.1389  -1.734 0.082980 .  
weekdayWednesday        -2.4169     3.1339  -0.771 0.440578    
weekdayThursday         -3.7139     3.1316  -1.186 0.235669    
weekdayFriday            0.9168     3.1234   0.294 0.769126    
workingdayWorkingDay         NA         NA      NA       NA    
weathersitMisty         -6.3713     2.0774  -3.067 0.002166 ** 
weathersitLightPrecip  -60.3711     3.5025 -17.236  &lt; 2e-16 ***
weathersitHeavyPrecip  -33.1693    63.7637  -0.520 0.602937    
temp                   195.1921    31.9175   6.116 9.83e-10 ***
atemp                  103.9531    33.1547   3.135 0.001719 ** 
hum                   -114.9024     5.9797 -19.216  &lt; 2e-16 ***
windspeed              -43.2351     7.6305  -5.666 1.48e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 110.2 on 17327 degrees of freedom
Multiple R-squared:  0.6323,    Adjusted R-squared:  0.6312 
F-statistic: 584.2 on 51 and 17327 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>emptymod <span class="ot">=</span> <span class="fu">lm</span>(count <span class="sc">~</span><span class="dv">1</span>, bike6) <span class="co">#use ~1 to build an empty model </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(emptymod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count ~ 1, data = bike6)

Residuals:
    Min      1Q  Median      3Q     Max 
-188.46 -149.46  -47.46   91.54  787.54 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  189.463      1.376   137.7   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 181.4 on 17378 degrees of freedom</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>backmod <span class="ot">=</span> <span class="fu">stepAIC</span>(allmod, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">trace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=163480.3
count ~ season + mnth + hr + holiday + weekday + workingday + 
    weathersit + temp + atemp + hum + windspeed


Step:  AIC=163480.3
count ~ season + mnth + hr + holiday + weekday + weathersit + 
    temp + atemp + hum + windspeed

             Df Sum of Sq       RSS    AIC
&lt;none&gt;                    210249597 163480
- atemp       1    119288 210368885 163488
- weekday     6    408229 210657827 163502
- holiday     1    302516 210552113 163503
- windspeed   1    389568 210639166 163510
- temp        1    453813 210703411 163516
- season      3   2395881 212645479 163671
- mnth       11   2703565 212953162 163680
- weathersit  3   3664116 213913714 163775
- hum         1   4480401 214729999 163845
- hr         23 189158302 399407899 174586</code></pre>
</div>
</div>
<p>Question 12 Which two variables combine to make workingday? B. Weekday and holiday</p>
<p>Question 13: Which variable is removed? workingday</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>